language: bash
services: docker

env:
  - VERSION=glibc
  - VERSION=musl
  - VERSION=uclibc

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - image="busybox:$VERSION"

script:
  - ./build.sh "$VERSION"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
